services:
  db:
    image: postgres:15-alpine
    container_name: cv-simple-checker-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRESS_DB: cv_simple_checker
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data # Persist database data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cv-simple-checker-app
    container_name: cv-simple-checker-app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
volumes:
  db_data:
